# Remove version line to use compose specification

services:
  app:
    image: kristianyourpay/levelup-app:latest
    container_name: levelup-app
    restart: unless-stopped
    networks:
      - levelup-network
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=levelup
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_CONNECTION_INDONESIA_TERRITORY=mysql
      - DB_HOST_INDONESIA_TERRITORY=mysql
      - DB_PORT_INDONESIA_TERRITORY=3306
      - DB_DATABASE_INDONESIA_TERRITORY=indonesia_territory
      - DB_USERNAME_INDONESIA_TERRITORY=root
      - DB_PASSWORD_INDONESIA_TERRITORY=secret
    depends_on:
      db:
        condition: service_healthy
      mysql:
        condition: service_healthy

  webserver:
    image: nginx:alpine
    container_name: levelup-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - levelup-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: levelup-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=levelup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - levelup-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: levelup-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: indonesia_territory
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-compose/mysql/init_db_terriroty.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - levelup-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -psecret"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: levelup-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - levelup-network

volumes:
  postgres-data:
  mysql-data:
  redis-data:

networks:
  levelup-network:
    driver: bridge 